spring:

  datasource:
    url: 'jdbc:postgresql://localhost:5432/user-service-db'
    username: 'postgres'
    password: 'postgres'

  cache:
    type: 'redis'
    redis:
      host: 'localhost'
      port: '6379'

server:
  port: '8080'
