spring:
  application:
    name: 'user-service'

  profiles:
    active: 'local'

  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 50
        one-indexed-parameters: 'true'

  datasource:
    driverClassName: 'org.postgresql.Driver'
    hikari:
      maximum-pool-size: 20

  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: 'validate'
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: 'app'

  liquibase:
    enabled: 'true'
    change-log: 'classpath:/db/changelog/db.changelog-master.yml'
    default-schema: 'app'

logging:
  level:
    root: 'info'

# Custom properties
application:
  cache:
    redis:
      time-to-live-in-minutes: 5
  security:
    enabled: 'true'
    secretKey: "${TOKEN_SECRET}"
