spring:
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  docker:
    compose:
      enabled: 'true'

  cache:
    type: 'redis'
    redis:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"
